export type SortConfig = { key: keyof UserData; direction: 'asc' | 'desc' };

export type UserData = {
  id: string;
  age: number;
  gender: string;
  incomeLevel: string;
  education: string;
  region: string;
  industry: string;
  digitalEngagementScore: number;
  primaryDevice: string;
  secondaryDevice?: string;
  internetSpeed?: string;
  socialMediaUsage?: string;
  ecommerceFrequency: string;
  workStyle?: string;
  commuteTime?: number;
  fitnessLevel: string;
  dietaryPreference?: string;
  travelFrequency?: string;
  brandLoyalty: string | number;
  priceSensitivity: string | number;
  shoppingChannel: string;
  productResearch?: string;
  reviewInfluence?: string;
  healthStatus: string;
  stressLevel: string;
  sleepQuality: string;
  mentalHealthAwareness?: string;
  preventiveCare?: string;
  environmentalConsciousness?: string;
  communityInvolvement?: string;
  politicalEngagement?: string;
  volunteerFrequency?: string;
  investmentExperience: string;
  riskTolerance?: string;
  savingsRate?: string;
  debtLevel?: string;
  financialGoals?: string;
  communicationStyle?: string;
  relationshipStatus?: string;
  familySize?: number;
  petOwnership?: string;
  socialCircle?: string;
  learningStyle?: string;
  skillDevelopment?: string;
  languageSkills?: number;
  certificationCount?: number;
  mentorshipRole?: string;
  techAdoption?: string;
  aiComfort?: string;
  automationPreference?: string;
  dataPrivacy?: string;
  timeZone?: string;
  workHours?: string;
  peakProductivity?: string;
  decisionMaking?: string;
  changeAdaptability?: string;
};


